/**
 * Export Backport Command
 *
 * Generates or applies backport bundles to target skills.
 * Backports copy Aha Card learnings into permanent skill documentation.
 *
 * @module self-learning/commands/export-backport
 */

import { mkdir } from "fs/promises";
import { ok, err, makeError } from "../types/result";
import type { AsyncResult } from "../types/result";
import type { AhaCard } from "../types/aha-card";
import type { Signal } from "../types/signal";
import type { BackportRecord, BackportChange, BackportManifest } from "../types/backport";
import {
  AHA_CARD_START_MARKER,
  AHA_CARD_END_MARKER,
  AHA_FILE_HEADER_MARKER,
} from "../types/backport";
import { MIN_BACKPORT_SCORE } from "../types/signal";
import {
  findRepoRoot,
  getProjectStore,
  ensureStoreDirs,
  getStorePath,
  FILES,
  safeUserSlug,
} from "../lib/store";
import { readJsonl, appendJsonl, firstAndLatestById } from "../lib/jsonl";
import { backportId, sigId } from "../lib/id-generator";
import { isoNow } from "../lib/timestamp";
import {
  calculateScoreBreakdown,
  isBackportCandidate,
} from "../lib/scoring";
import { registerCommand, getFlag, getBoolFlag } from "./index";
import type { ParsedArgs } from "./index";

// =============================================================================
// Types
// =============================================================================

interface ExportBackportResult {
  ok: boolean;
  repo_root: string;
  user: string;
  project_store: string;
  manifest: BackportManifest;
  diff?: string;
  applied: boolean;
  signals_recorded: number;
}

// =============================================================================
// Helpers
// =============================================================================

/**
 * Generate markdown content for an Aha Card.
 */
function renderAhaCard(card: AhaCard): string {
  const lines: string[] = [];

  lines.push(`${AHA_CARD_START_MARKER} id="${card.id}" -->`);
  lines.push(`### ${card.title}`);
  lines.push("");

  if (card.when_to_use) {
    lines.push(`**When to use:** ${card.when_to_use}`);
    lines.push("");
  }

  if (card.problem) {
    lines.push(`**Problem:** ${card.problem}`);
    lines.push("");
  }

  if (card.solution_steps && card.solution_steps.length > 0) {
    lines.push("**Solution:**");
    for (const step of card.solution_steps) {
      lines.push(`- ${step}`);
    }
    lines.push("");
  }

  if (card.gotchas && card.gotchas.length > 0) {
    lines.push("**Gotchas:**");
    for (const gotcha of card.gotchas) {
      lines.push(`- ${gotcha}`);
    }
    lines.push("");
  }

  if (card.tags && card.tags.length > 0) {
    lines.push(`**Tags:** ${card.tags.join(", ")}`);
    lines.push("");
  }

  lines.push(AHA_CARD_END_MARKER);

  return lines.join("\n");
}

/**
 * Generate the reference file content for backported cards.
 */
function generateReferenceFile(cards: AhaCard[], skillName: string, backportIdStr: string): string {
  const lines: string[] = [];

  lines.push(`${AHA_FILE_HEADER_MARKER} skill="${skillName}" backport="${backportIdStr}" -->`);
  lines.push(`# Self-Learning Aha Cards`);
  lines.push("");
  lines.push(`> Auto-generated by self-learning backport. Do not edit directly.`);
  lines.push(`>`);
  lines.push(`> Backport ID: ${backportIdStr}`);
  lines.push(`> Generated: ${isoNow()}`);
  lines.push("");

  for (const card of cards) {
    lines.push(renderAhaCard(card));
    lines.push("");
  }

  return lines.join("\n");
}

/**
 * Generate a diff showing what would change.
 */
function generateDiff(
  skillPath: string,
  refFileName: string,
  content: string,
  existingContent: string | null
): string {
  const lines: string[] = [];
  const fullPath = `${skillPath}/references/${refFileName}`;

  if (existingContent === null) {
    lines.push(`--- /dev/null`);
    lines.push(`+++ ${fullPath}`);
    lines.push(`@@ -0,0 +1,${content.split("\n").length} @@`);
    for (const line of content.split("\n")) {
      lines.push(`+${line}`);
    }
  } else {
    lines.push(`--- ${fullPath}`);
    lines.push(`+++ ${fullPath}`);
    // Simple diff - show removed and added sections
    const oldLines = existingContent.split("\n");
    const newLines = content.split("\n");
    lines.push(`@@ -1,${oldLines.length} +1,${newLines.length} @@`);
    for (const line of oldLines) {
      lines.push(`-${line}`);
    }
    for (const line of newLines) {
      lines.push(`+${line}`);
    }
  }

  return lines.join("\n");
}

/**
 * Read file content or return null if doesn't exist.
 */
async function readFileOrNull(path: string): Promise<string | null> {
  try {
    const file = Bun.file(path);
    if (await file.exists()) {
      return await file.text();
    }
    return null;
  } catch {
    return null;
  }
}

/**
 * Extract existing card IDs from a reference file.
 */
function extractExistingCardIds(content: string): string[] {
  const ids: string[] = [];
  const regex = new RegExp(`${AHA_CARD_START_MARKER.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\s+id="([^"]+)"`, 'g');
  let match;
  while ((match = regex.exec(content)) !== null) {
    ids.push(match[1]);
  }
  return ids;
}

// =============================================================================
// Command Implementation
// =============================================================================

async function exportBackportCommand(args: ParsedArgs): AsyncResult<void> {
  const skillPath = getFlag(args, "skill-path");
  const idsArg = getFlag(args, "ids");
  const makeDiff = getBoolFlag(args, "make-diff");
  const apply = getBoolFlag(args, "apply");
  const minScore = parseInt(getFlag(args, "min-score") ?? String(MIN_BACKPORT_SCORE), 10);
  const limit = parseInt(getFlag(args, "limit") ?? "10", 10);
  const context = getFlag(args, "context");

  if (!skillPath) {
    return err(makeError("INVALID_PAYLOAD", "Provide --skill-path <path-to-skill-directory>"));
  }

  if (makeDiff && apply) {
    return err(makeError("INVALID_PAYLOAD", "Cannot use both --make-diff and --apply"));
  }

  // Find repository root
  const repoRoot = await findRepoRoot();
  if (repoRoot === null) {
    return err(
      makeError(
        "STORE_NOT_FOUND",
        "Not in a git repository. Run this command from within a git repo."
      )
    );
  }

  const user = safeUserSlug();
  const storeDir = getProjectStore(repoRoot);

  // Ensure store exists
  const dirResult = await ensureStoreDirs(storeDir);
  if (!dirResult.success) {
    return dirResult;
  }

  // Load data
  const ahaResult = await readJsonl<AhaCard>(getStorePath(storeDir, FILES.AHA_CARDS));
  const sigResult = await readJsonl<Signal>(getStorePath(storeDir, FILES.SIGNALS));
  const bpResult = await readJsonl<BackportRecord>(getStorePath(storeDir, FILES.BACKPORTS));

  if (!ahaResult.success) return ahaResult;
  if (!sigResult.success) return sigResult;
  if (!bpResult.success) return bpResult;

  const signals = sigResult.value.records;
  const { latest: ahaLatest } = firstAndLatestById(ahaResult.value.records);

  // Resolve target skill name from path
  const skillName = skillPath.split("/").pop() ?? "unknown";

  // Determine which cards to backport
  let requestedCardIds: string[] = [];

  if (idsArg) {
    // Explicit IDs provided
    requestedCardIds = idsArg.split(",").map((id) => id.trim()).filter(Boolean);
  } else {
    // Auto-select backport candidates based on scoring
    for (const [ahaId, card] of ahaLatest) {
      const breakdown = calculateScoreBreakdown(ahaId, signals);
      if (isBackportCandidate(card, breakdown, minScore)) {
        requestedCardIds.push(ahaId);
      }
    }
    requestedCardIds = requestedCardIds.slice(0, limit);
  }

  if (requestedCardIds.length === 0) {
    console.log(JSON.stringify({
      ok: true,
      message: "No cards to backport. Either provide --ids or ensure cards meet backport criteria (shareable=true, score >= min-score).",
      candidates_checked: ahaLatest.size,
      min_score: minScore,
    }, null, 2));
    return ok(undefined);
  }

  // Validate requested card IDs exist
  const cardsToBackport: AhaCard[] = [];
  for (const id of requestedCardIds) {
    const card = ahaLatest.get(id);
    if (!card) {
      return err(makeError("NOT_FOUND", `Aha card "${id}" not found`));
    }
    cardsToBackport.push(card);
  }

  // Check for existing backported cards
  const refFileName = "self-learning-aha.md";
  const refFilePath = `${skillPath}/references/${refFileName}`;
  const existingContent = await readFileOrNull(refFilePath);
  const existingCardIds = existingContent ? extractExistingCardIds(existingContent) : [];

  // Filter out already backported cards
  const newCards = cardsToBackport.filter((c) => !existingCardIds.includes(c.id));
  const addedCardIds = newCards.map((c) => c.id);
  const resultCardIds = [...existingCardIds, ...addedCardIds];

  // Generate the backport ID
  const bpId = backportId(skillName, requestedCardIds);

  // Generate the reference file content
  const allCards = [...cardsToBackport.filter((c) => existingCardIds.includes(c.id)), ...newCards];
  const refContent = generateReferenceFile(allCards.length > 0 ? allCards : cardsToBackport, skillName, bpId);

  // Determine changes
  const changes: BackportChange[] = [];
  if (existingContent === null) {
    changes.push({ path: `references/${refFileName}`, kind: "created" });
  } else if (newCards.length > 0) {
    changes.push({ path: `references/${refFileName}`, kind: "modified" });
  }

  // Build manifest
  const manifest: BackportManifest = {
    backport_id: bpId,
    generated_at: isoNow(),
    target_skill_name: skillName,
    target_skill_path: skillPath,
    requested_card_ids: requestedCardIds,
    existing_card_ids: existingCardIds,
    added_card_ids: addedCardIds,
    result_card_ids: resultCardIds,
    changes,
  };

  // Generate diff if requested
  let diff: string | undefined;
  if (makeDiff || (!apply && !makeDiff)) {
    diff = generateDiff(skillPath, refFileName, refContent, existingContent);
  }

  // Apply changes if requested
  let signalsRecorded = 0;
  if (apply) {
    // Ensure references directory exists
    const refsDir = `${skillPath}/references`;
    try {
      await mkdir(refsDir, { recursive: true });
    } catch {
      // Directory may already exist
    }

    // Write the reference file
    await Bun.write(refFilePath, refContent);

    // Record backport
    const backportRecord: BackportRecord = {
      ...manifest,
      applied: true,
    };
    const backportPath = getStorePath(storeDir, FILES.BACKPORTS);
    await appendJsonl(backportPath, backportRecord);

    // Record signals for each backported card
    const ts = isoNow();
    const signalsPath = getStorePath(storeDir, FILES.SIGNALS);
    for (const cardId of addedCardIds) {
      const signal: Signal = {
        id: sigId("aha_backported", cardId, ts),
        ts,
        kind: "aha_backported",
        aha_id: cardId,
        source: "export-backport",
        context: context ?? `Backported to ${skillName}`,
      };
      await appendJsonl(signalsPath, signal);
      signalsRecorded++;
    }

    // Update aha cards to backported status
    const ahaPath = getStorePath(storeDir, FILES.AHA_CARDS);
    for (const card of newCards) {
      const updatedCard: AhaCard = {
        ...card,
        status: "backported",
        ts,
        last_touched_ts: ts,
        note: `Backported to ${skillName} (${bpId})`,
      };
      await appendJsonl(ahaPath, updatedCard);
    }
  }

  const result: ExportBackportResult = {
    ok: true,
    repo_root: repoRoot,
    user,
    project_store: storeDir,
    manifest,
    diff,
    applied: apply,
    signals_recorded: signalsRecorded,
  };

  console.log(JSON.stringify(result, null, 2));
  return ok(undefined);
}

// =============================================================================
// Registration
// =============================================================================

registerCommand({
  name: "export-backport",
  description: "Generate or apply backport bundles to skills",
  usage:
    "export-backport --skill-path <path> [options]\n\n" +
    "  --skill-path <path>  Path to target skill directory (required)\n" +
    "  --ids <id1,id2>      Comma-separated aha card IDs to backport\n" +
    "  --make-diff          Show diff without applying (default if no --apply)\n" +
    "  --apply              Apply the backport changes\n" +
    "  --min-score <n>      Min score for auto-selecting candidates (default: 4)\n" +
    "  --limit <n>          Max cards to auto-select (default: 10)\n" +
    "  --context <text>     Optional context for signals\n\n" +
    "Examples:\n" +
    "  # Preview backport to beads skill\n" +
    "  export-backport --skill-path .claude/skills/beads --make-diff\n\n" +
    "  # Backport specific cards\n" +
    "  export-backport --skill-path .claude/skills/beads --ids aha_abc,aha_def --apply",
  handler: exportBackportCommand,
});
