/**
 * Init Command
 *
 * Initializes the self-learning store in the current repository.
 * Creates directories and updates .gitignore.
 *
 * @module self-learning/commands/init
 */

import { ok, err, makeError } from "../types/result";
import type { AsyncResult } from "../types/result";
import {
  findRepoRoot,
  getProjectStore,
  ensureStoreDirs,
  updateGitignore,
  isStoreInitialized,
  getStorePath,
  FILES,
} from "../lib/store";
import { registerCommand, getBoolFlag } from "./index";
import type { ParsedArgs } from "./index";

// =============================================================================
// Command Implementation
// =============================================================================

async function initCommand(args: ParsedArgs): AsyncResult<void> {
  const noGitignore = getBoolFlag(args, "no-gitignore");

  // Find repository root
  const repoRoot = await findRepoRoot();
  if (repoRoot === null) {
    return err(
      makeError(
        "STORE_NOT_FOUND",
        "Not in a git repository. Run this command from within a git repo."
      )
    );
  }

  const storeDir = getProjectStore(repoRoot);

  // Check if already initialized
  if (await isStoreInitialized(storeDir)) {
    console.log(`Store already initialized at: ${storeDir}`);
    return ok(undefined);
  }

  // Create directories
  const dirResult = await ensureStoreDirs(storeDir);
  if (!dirResult.success) {
    return dirResult;
  }

  // Create empty JSONL files
  const files = [
    FILES.AHA_CARDS,
    FILES.RECOMMENDATIONS,
    FILES.SIGNALS,
    FILES.EVENTS,
    FILES.BACKPORTS,
  ];

  for (const file of files) {
    const path = getStorePath(storeDir, file);
    const bunFile = Bun.file(path);
    if (!(await bunFile.exists())) {
      await Bun.write(path, "");
    }
  }

  // Create initial INDEX.md
  const indexPath = getStorePath(storeDir, FILES.INDEX);
  const indexContent = `# Self-Learning Index

*No learnings recorded yet.*

Run \`record\` to capture your first Aha Card.

---

*Generated by self-learning-skills (TypeScript)*
*Inspired by [Scott Falconer's self-learning-skills](https://github.com/scottfalconer/self-learning-skills)*
`;
  await Bun.write(indexPath, indexContent);

  // Update .gitignore
  if (!noGitignore) {
    const gitignoreResult = await updateGitignore(repoRoot);
    if (!gitignoreResult.success) {
      console.warn(`Warning: ${gitignoreResult.error.message}`);
    }
  }

  console.log(`Initialized self-learning store at: ${storeDir}`);
  if (!noGitignore) {
    console.log("Added .agent-skills/ to .gitignore");
  }

  return ok(undefined);
}

// =============================================================================
// Registration
// =============================================================================

registerCommand({
  name: "init",
  description: "Initialize self-learning store in current repository",
  usage: "init [--no-gitignore]",
  handler: initCommand,
});
